### PR TITLE
extra spaces are displayed; fixed grammar

### PR DESCRIPTION
**Pull request by Fornost461**
Tried to fix a few case issues, punctuation, and stuff.

### CODE REVIEW

**Comment by BackOrder** [comment]
Double spacing seems to have been a legacy styling since the early days. I am not against changing them but there are roughly 400 double spacings or so, which would require to change them all or nothing. Did you look at the changes through the manual to see how it affects the rendering?

The grammar corrections seems to be on point.

**Comment by ccoupe** [comment]
I happen not to care about two spaces vs one after a sentence close  We all know the manual markup is way too sensitive to line breaks however. God only knows how many people have touched the text in_'their_ voice, hoping to make it newbie relevant,, light but helpful. Impossible task but we all try.

It should be noted that @Fornost461 forked the shoes3 repo, created a branch on that repo, 'patch-1' and created a pull request so (s)he is  more git knowledgeable than I or @BackOrder .

**Comment by BackOrder** [comment]
Isn't it a bit early to commit this change? We both agree that either way would be acceptable. However, as far as spacing goes, it is an incomplete change at the moment.

It's refreshing to see someone who knows how to use git and GitHub. Maybe he will teach us a few things along the way. :D

**Comment by Fornost461** [comment]
Uh… I learned a long time ago how to do these git tricks with the command line, but I don't remember them much, so I just used the GitHub web interface and it did the heavy lifting (fork, branch creation and pull request) under my clueless supervision. I usually use GitHub alone, so I'm quite new to using it for collaborative projects. I'll try not to mix grammar edits with spaces edits the next time.

> Did you look at the changes through the manual to see how it affects the rendering?

I looked at the changes through the manual and it seems fine to me, except I noticed another grammar issue: line 75, _every platforms_ instead of _every platform_. Do I create a new pull request just for that?

**Comment by BackOrder** [comment]
> RE: GitHub

We had our challenges when it comes to Git and GitHub. We even created a [Git, Github and Shoes](https://github.com/shoes/shoes3/wiki/Git,-Github-and-Shoes) wiki page to help us. Perhaps you would like to contribute on how you did your new pull request from a fork? That could help new contributors.

>  I'll try not to mix grammar edits with spaces edits the next time.

Really no problem here. It would be best to be consistent but we will survive on this one. Your contribution is appreciated.

> I looked at the changes through the manual and it seems fine to me, except I noticed another grammar issue: line 75, every platforms instead of every platform. Do I create a new pull request just for that?

It's up to you. Ideal situation would be that you perform the changes on your repo until you are done and submit your set of commits as one pull request.

**Comment by ccoupe** [comment]
>  Isn't it a bit early to commit this change?

Uhh.. No!   It's the damn manual!  Its been incorrect from day one, Incremental improvements is what we do. Perfection is  in some other project.

> Do I create a new pull request just for that? 

I wouldn't,  but I'm not you.  Git will warn you on the next commit that you haven't 'add;ed that.
Thanks for helping out @Fornost461

**Comment by dredknight** [comment]
Hm.. I just understood what pull request means ( I knew what it do I was not sure why it was call pull because you actually push a change to the cloud).

If I am not wrong Pull means a request to pull your change into the master? :D

**Comment by Fornost461** [comment]
> we will survive on this one.

Yay!

> Perhaps you would like to contribute on how you did your new pull request from a fork

Since I only used the web interface, my “technique” involved copy-pasting the contents of my local file onto GitHub, which is clearly not terribly advisable. I could however try to sum up the technique described [there](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project).

> Thanks for helping out

You're welcome!

> Pull means a request to pull your change into the master?

Yes, as far as I know, a pull request is a request to merge your branch into another branch.

**Comment by ccoupe** [comment]
> Pull means a request to pull your change into the master?

Mostly. The main repository  is https://github.com/shoes/shoes3.  @BackOrder, @Fornost461  have 'forks' of it.  They hav their copies at github.com/???/shoes3 and a local copy on their machine(s)  they work on their  machine and when they are done they 'push' the changes to _their_ github repo Then They create a  pull request (PR) to merge their repo's changes to the github/shoes/shoes3 repo, I as admin, then merge their changes and fix any conflicts. That's Idyllic.  I am a little different because I can push changes to the shoes/shoes3 repo without asking for a pull request to be reviewed. 

Each repo can have branches.  Master is the main branch a branch is essentially a copy of master at the time the branch was created. Branches can be local only or both local and remote. Shoes typically has both. For example I'm doing the #383 event stuff in branch 'event'  and some font setting things in 'widgetfont' branch.  I will eventually merge them to my master branch and push the mess up to my remote master branch shoes/shoes3/master. If @BackOrder, for example attempts to push a change to his github repo he gets a message that something has changed at shoes/shoes3. He needs to 'pull' the changes I made down to his repo(s)/branchs(s) and resolve any conflicts between his code and what I did and then he can push to his remote repo and issue a pull request (PR) from his repo/branch to shoes/shoes3  Errors happen.  Things can get mis configured,  and short cuts exist - like @Fornost461 editing on the website. I tend to do that with shoes.rb.com repo so I'm not shaking my finger at anyone.  I see I have another pull request to attend to.

**Comment by Fornost461** [comment]
I made a [wiki page](https://github.com/shoes/shoes3/wiki/Git,-Github-and-Shoes-%E2%80%93-with-a-fork-and-pull-requests) about using a fork.

**Comment by BackOrder** [comment]
> I made a wiki page about using a fork.

Oh, wow. This is really well written. Thanks!

**Comment by Fornost461** [comment]
Thank you very much!

**Pull request merged**
